repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.21
    hooks:
      - id: ruff-check
        # https://docs.astral.sh/ruff/rules
        args: ["--select=FAST001,FAST002,FAST003,F841,RUF059,B007,ARG001"]
      - id: ruff-format
  - repo: local
    hooks:
      - id: ty
        name: ty check
        entry: uv run ty check .
        language: python
        files: ^app/
